[font]
size = 14.0
normal = { family = "Hack Nerd Font" }

[window]
decorations = "Buttonless"
opacity = 0.85
padding = { x = 12, y = 12 }
option_as_alt = "Both"

[general]
import = [
  "~/.config/alacritty/iris.toml",
  # "~/.config/alacritty/rose-pine-moon.toml",
  # "~/.config/alacritty/pencil_dark.toml",
  # "~/.config/alacritty/rose-pine.toml",
  # "~/.config/alacritty/rose-pine-dawn.toml",
]

[env]
TERM = "xterm-256color"
